### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by sradu** [algolia/color-extractor#5]
Is this project still maintained? I found two bugs inside resize that makes the project unusable and no updates for a year.

**Comment by ercolanelli-leo** [comment]
Thanks for the interest!

Indeed it was more seen as an experiment, however I would be happy to help with the issue! Could you describe a bit more the bug you are facing?

**Comment by sradu** [comment]
It's all good, Leo, thank you. We've actually figured out another way of doing it.

Thank you though!

**Comment by redox** [comment]
> It's all good, Leo, thank you. We've actually figured out another way of doing it.
> 
> Thank you though!

Hey @sradu, could you still tell us a bit more about those resizing bugs? We would love to understand your initial struggles 🥇
